#Jetpack Plugin

#Fuel consumption in seconds
burn-rate: 5

#Fuel item meta data (Recommended to use: /jetpack set fuel)
fuel-item:
  ==: org.bukkit.inventory.ItemStack
  v: 1519
  type: COAL

#Jetpack item meta data (Recommended to use: /jetpack set jetpack)
jetpack-item:
  ==: org.bukkit.inventory.ItemStack
  v: 1519
  type: CHAINMAIL_CHESTPLATE
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: '&3Jetpack'
    lore:
    - '&7Sneak to toggle on/off'
    - '&7Double tap space to fly'

#Particle ejected from the jetpack when flying (Set '' for none)
jetpack-particle: 'CLOUD'
#Number of particle on jetpack
jetpack-particle-amount: 0
#RGB Code for redstone particle
jetpack-redstone-particle: '255,255,0'

#Messages for the plugin
messages:
  prefix: "&f[&8Jetpack&f]"
  no-permission: "&cYou don't have permission."
  hand-air: "&cYou have nothing on your hand."
  hand-not-chestplate: "&cItem must be a chestplate."
  player-not-found: "&cPlayer not found."
  amount-overload: "&cPlayer's inventory would be full if you give more!"
  jetpack:
    turn-on: "&aJetpack on"
    turn-off: "&cJetpack off"
    out-of-fuel: "&cJetpack ran out of fuel"
    need-fuel: "&cYou need fuel!"
    not-numeric: "&cAmount must be a number!"
    amount-overload: "&cPlayer's inventory would be full if you give more!"
  commands:
    reload: "&aConfig reloaded."
    jetpack:
      give-obtain: "{amount}x &aJetpack received!"
      give-sender: "&aGiven &2{amount}x jetpack to &2{player}&a."
      set: "&aJetpack Item set."
    fuel:
      give-obtain: "{amount}x &aFuel received!"
      give-sender: "&aGiven &2{amount}x fuel to &2{player}&a."
      set: "&aFuel Item set."