main: me.blekdigits.jetpack.JetpackPlugin
version: 4.0.0
name: Jetpack
author: Blekdigits
api-version: 1.21
commands:
  jetpack:
    description: Main command for the Jetpack plugin
    usage: /jetpack <give|set|reload>
    permission: jetpack.admin

permissions:
  jetpack.admin:
    description: Allows configuring and giving jetpacks.
    default: op
  jetpack.use:
    description: Allows a player to activate and fly with the jetpack.
    default: true